### ISSUE TITLE
한글 지원 가능하게 업데이트 해주시면 안 될까요? 초보자라서 응용이 안 됩니다. ㅠ

### ISSUE THREAD

**Issue by coboooo** [PhillyAI/GlobalHook#6]
...

**Comment by 20chan** [comment]
한글 지원이라는게 이해가 안되는데 어떤걸 하시려는건가요?

**Comment by coboooo** [comment]
아 한영키를 눌러서 한글 상태에서 입력하면 영어가 입력이 되더라구요. 한글 상태에서 한글을 후킹하고 싶습니다.

**Comment by 20chan** [comment]
여기서 사용하는 키보드 시뮬레이션은 물리적 키보드 입력에 조금 더 가까워서 한/영 상태를 확인하지는 않습니다.
원하는 텍스트를 그대로 입력하는거라면 [SendKeys.Send](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.sendkeys.send?redirectedfrom=MSDN&view=windowsdesktop-5.0#System_Windows_Forms_SendKeys_Send_System_String_) 를 사용하는게 나을 것 같고,
한/영 상태를 확인하거나 바꾸길 원하신다면 IME api [ImmGetContext](https://warpfence.tistory.com/m/entry/C-IME-%EC%98%81%EB%AC%B8-%EB%B0%8F-%EB%8C%80%EB%AC%B8%EC%9E%90-%EB%B3%80%ED%99%98) 등을 사용하는게 좋을 듯 합니다.

**Comment by coboooo** [comment]
네 알겠습니다. 초보자이지만 검색을 해서 해보겠습니다. 그리고 혹시 https://kin.naver.com/qna/detail.naver?d1id=1&dirId=1040104&docId=403695002 이 게시물을 읽어봐 주시겠어요? 인터넷에 있는 한글 후킹 코드를 실행해봤는데 에러가 떠서 올린 질문입니다.

**Comment by 20chan** [comment]
올려주신 링크가 이 이슈와 관계있는 내용이 아닌것 같은데 다시 한번 확인해주시겠어요?

**Comment by coboooo** [comment]
아이고 링크를 잘못 올렸네요 https://kin.naver.com/qna/detail.naver?d1id=1&dirId=1040102&docId=403685914 이 링크입니다.

**Comment by 20chan** [comment]
질문에 어떤 에러가 발생하는지 나와 있지 않아 확인하기 어렵네요. 에러 메시지 첨부해주셔야 문제를 파악하기 쉽습니다.
해당 문제는 아마 크로스스레드 문제일거고 `dataGridView1.BeginEdit` 같은 경우에는 winform ui 스레드에서 실행해야 해서 [`Invoke`](https://bufferover.tistory.com/3) 관련해서 찾아보시면 도움이 될 것 같습니다.
CommonObj는 컨텍스트가 아예 없어서 모르겠네요

**Comment by coboooo** [comment]
답변 감사드립니다. 혹시라도 나중에 시간이 나시면 지식인 게시물의 하단에 myhook3.zip 파일의 소스도 검토해주시면 정말 감사하겠습니다. 참고로 저 코드는 구글에서 'C# 한글 후킹' 이렇게 검색해서 나오는 가장 위 게시물을 가져온 코드입니다.
